---
- hosts: all
  gather_facts: false
  connection: local
  #vars:
  #  #  ansible_python_interpreter: "{{ansible_playbook_python}}"

  tasks:
  - name: "Crear vapp"
    vcd_vapp:
     vapp_name: "pruebaansible"
     vdc: "vDC_Autoconsumo_Implementacion_B2B2"
     state: "present"
